version: '1.0'

services:
  api:
    image: video_stream:1.0
    depends_on:
      - mongo
    ports:
      - 3000:3000
    env_file:
      - .env

  mongo:
    image: mongo:8
    ports:
      - 27017:27017
    volumes:
      - test_data:/data/db

volumes:
  test_data: